### ISSUE TITLE
Players can write using characters not added to specific chapter

### ISSUE THREAD

**Issue by drikqlis** [KrystianKempski/DagoniteEmpire#16]
Players can see and write using a character which is not added to a chapter if their other character is added there. Can't test with different users as registration does not work.

**Comment by KrystianKempski** [comment]
should be fixed now

**Comment by drikqlis** [comment]
Still present:
![image](https://github.com/user-attachments/assets/eebacfdd-f591-4b98-98c5-3186fca6033c)
![image](https://github.com/user-attachments/assets/b84e7f8c-f56e-4f12-824f-12b51e1f4522)
